# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-09-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190915_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='性别'),
        ),
    ]
